version: '2'
services:
  zookeeper:
    restart: always
    image: wurstmeister/zookeeper
    ports:
        - "2181:2181"
# cluster
  kafka-1:
    restart: always
    image: kafka-docker_kafka
    ports:
        - "9092:9092"
    build: .
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.18.0.2 # 这个 host 是用于集群外的 client 连接集群用的 host; 等同于让客户端来决定段域
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka-2:
    restart: always
    image: kafka-docker_kafka
    ports:
        - "9093:9092"
    build: .
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.18.0.2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka-3:
    restart: always
    image: kafka-docker_kafka
    ports:
        - "9094:9092"
    build: .
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.18.0.2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
