version: '2'
services:
  zookeeper:
    restart: always
    image: wurstmeister/zookeeper
  kafka:
    restart: always
    build: .
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.18.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
